name: Go CI

on:
  push:
    branches:
      - master
      - develop
      - fix/*
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16' # The Go version to download (if necessary) and use.
      - name: Build
        run: go build -v .
